name: tune_wave
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  intl: ^0.19.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/images/
    - assets/song_images/
    - assets/songs/


  uses-material-design: true


